name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'getANSIfrequencies.m'
        destination_repo: 'jmrplens/getANSIfrequencies'
        destination_folder: '/'
        user_email: 'joreple@upv.es'
        user_name: 'jmrplens'